//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK.BaseballTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGame
    {
        public System.Guid GameId { get; set; }
        public System.Guid OpposingTeamId { get; set; }
        public System.Guid TeamId { get; set; }
        public Nullable<int> TeamScore { get; set; }
        public Nullable<int> OpposingTeamScore { get; set; }
        public bool Home { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tblTeam tblTeam { get; set; }
        public virtual tblTeam tblTeam1 { get; set; }
    }
}
