//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MK.BaseballTracker.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserTeam
    {
        public System.Guid UserTeamId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid TeamId { get; set; }
    
        public virtual tblTeam tblTeam { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
